import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/app/src/context/AuthContext";

export const metadata: Metadata = {
  title: "Recetas Ricas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
          {children}
      </body>
    </html>
        </AuthProvider>
  );
}
